name: Windows Build

on:
  workflow_dispatch:
  schedule:
    # run every 24 hours
    - cron: '0 */24 * * *'

permissions:
  contents: write

jobs:
  precheck:
    name: Fetch latest version & Check for existing release
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
      version: ${{ steps.setver.outputs.version }}
      title: ${{ steps.setver.outputs.title }}
      changelog: ${{ steps.setver.outputs.changelog }}
    steps:
      - name: Get latest Aseprite release info
        id: setver
        run: |
          release_info=$(curl -s https://api.github.com/repos/aseprite/aseprite/releases/latest)
          TAG=$(echo "$release_info" | jq -r .tag_name)
          VER=${TAG#v}
          TITLE=$(echo "$release_info" | jq -r .name)
          CHANGELOG=$(echo "$release_info" | jq -r .body)
          
          echo "version=$VER" >> $GITHUB_OUTPUT
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          
          # Escape newlines for multiline output
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Query GitHub API for release
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v${{ steps.setver.outputs.version }}"
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/USLTD/aseprite-builds/releases/tags/$TAG")
          if [ "$code" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build Aseprite
    runs-on: windows-latest
    needs: precheck
    if: needs.precheck.outputs.exists != 'true'
    strategy:
      matrix:
        arch: [x64, x86]
    env:
      VERSION: ${{ needs.precheck.outputs.version }}
      SCCACHE_GHA_ENABLED: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache sccache directory
        uses: actions/cache@v3
        with:
          path: |
            %USERPROFILE%\.cache\sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-sccache-


      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Set version
        id: version
        shell: pwsh
        run: |
          $latest = Invoke-RestMethod https://api.github.com/repos/aseprite/aseprite/releases/latest
          $ver = $latest.tag_name.TrimStart('v')
          echo "VERSION=$ver" >> $env:GITHUB_ENV

      - name: Download Aseprite source
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/aseprite/aseprite/releases/download/v$env:VERSION/Aseprite-v$env:VERSION-Source.zip" `
            -OutFile Source.zip

      - name: Unzip Source
        if: env.SKIP != 'true'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path C:\aseprite -Force | Out-Null
          Expand-Archive -Path "Source.zip" -DestinationPath C:\aseprite -Force

      - name: Download Skia
        if: env.SKIP != 'true'
        shell: pwsh
        run: |
          $url = if ("${{ matrix.arch }}" -eq "x64") {
            'https://github.com/aseprite/skia/releases/latest/download/Skia-Windows-Release-x64.zip'
          } else {
            'https://github.com/aseprite/skia/releases/latest/download/Skia-Windows-Release-x86.zip'
          }
          Invoke-WebRequest -Uri $url -OutFile "Skia.zip"

      - name: Unzip Skia
        if: env.SKIP != 'true'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path C:\deps\skia -Force | Out-Null
          Expand-Archive -Path "Skia.zip" -DestinationPath C:\deps\skia -Force

      - name: Setup MSVC
        if: env.SKIP != 'true'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Configure build
        if: env.SKIP != 'true'
        shell: pwsh
        run: |
          $archDir = if ("${{ matrix.arch }}" -eq "x64") { "Release-x64" } else { "Release-x86" }
          Push-Location C:\aseprite
          New-Item -ItemType Directory -Path build -Force | Out-Null
          Set-Location build
          cmake `
            -G Ninja .. `
            -DCMAKE_BUILD_TYPE=Release `
            -DLAF_BACKEND=skia `
            -DSKIA_DIR=C:\deps\skia `
            -DSKIA_LIBRARY_DIR=C:\deps\skia\out\$archDir `
            -DSKIA_LIBRARY=C:\deps\skia\out\$archDir\skia.lib `
            -DCMAKE_C_COMPILER_LAUNCHER=sccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache `
            -DCMAKE_C_FLAGS="/FS" `
            -DCMAKE_CXX_FLAGS="/FS"

      - name: Build aseprite
        if: env.SKIP != 'true'
        shell: pwsh
        run: |
          Push-Location C:\aseprite\build
          ninja aseprite
          $libcrypto = $null
          if ("${{ matrix.arch }}" -eq "x64") {
            if (Test-Path -Path "C:/Windows/SysWOW64/libcrypto-1_1-x64.dll") {
              $libcrypto = "C:/Windows/SysWOW64.libcrypto-1_1-x64.dll"
            } else {
              if (Test-Path -Path "C:/Windows/System32/libcrypto-1_1-x64.dll") {
                $libcrypto = "C:/Windows/System32/libcrypto-1_1-x64.dll"
              }
            }
          } else {
            if ("${{ matrix.arch }}" -eq "x86") {
              if (Test-Path -Path "C:/Windows/System32/libcrypto-1_1-x64.dll") {
                $libcrypto = "C:/Windows/System32/libcrypto-1_1-x64.dll"
              } else {
                if (Test-Path -Path "C:/Windows/System32/libcrypto-1_1.dll") {
                  $libcrypto = "C:/Windows/System32/libcrypto-1_1.dll"
                }
              }
            }
          }
          if ($libcrypto -ne $null) {
            Copy-Item -Path $libcrypto -Destination "./bin"
          }

      - name: Create Zip Archive
        shell: pwsh
        run: |
          $artifactName = "aseprite-v${{ env.VERSION }}-windows-${{ matrix.arch }}"
          Compress-Archive -Path C:\aseprite\build\bin\* -DestinationPath "C:\aseprite\build\$artifactName.zip"
          echo "artifact_path=C:\aseprite\build\$artifactName.zip" >> $GITHUB_OUTPUT
        id: zip_artifact

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-v${{ env.VERSION }}-windows-${{ matrix.arch }}
          path: ${{ steps.zip_artifact.outputs.artifact_path }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [precheck, build]
    if: needs.precheck.outputs.exists != 'true'
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ needs.precheck.outputs.version }}" \
            --repo USLTD/aseprite-builds \
            --title "${{ needs.precheck.outputs.title }}" \
            --notes "${{ needs.precheck.outputs.changelog }}" \
            artifacts/**/*.zip
          echo "Release v${{ needs.precheck.outputs.version }} created."
