name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the "Build" workflow run to release.'
        required: true

permissions:
  actions: read
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifacts from build workflow
        id: download
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run_id || github.event.workflow_run.id }}
          path: artifacts

      - name: Get version from artifact directory
        if: steps.download.outcome == 'success'
        id: version
        run: |
          VERSION=$(ls artifacts | grep -oP 'aseprite-v\K[^-]*' | head -n 1)
          
          if [ -z "$VERSION" ]; then
            echo "Could not determine version from downloaded artifacts. No release will be created."
            echo "version_found=false" >> $GITHUB_OUTPUT
          else
            echo "Found version $VERSION to release."
            echo "version_found=true" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Get Aseprite release info
        if: steps.version.outputs.version_found == 'true'
        id: setver
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          release_info=$(gh release view "v${{ steps.version.outputs.version }}" --repo aseprite/aseprite --json name,body)
          TITLE=$(echo "$release_info" | jq -r .name)
          CHANGELOG=$(echo "$release_info" | jq -r .body)
          
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create single-depth ZIP archives
        if: steps.version.outputs.version_found == 'true'
        run: |
          # Go into the parent directory for the downloaded artifacts
          cd artifacts
          # Loop through each downloaded artifact directory (e.g., aseprite-v1.3.14.2-windows-x64/)
          for dir in */; do
            # Name of the output zip file (e.g., aseprite-v1.3.14.2-windows-x64.zip)
            zip_file_name="${dir%/}.zip"
            echo "Creating $zip_file_name..."
            # Go into the artifact directory and zip its *contents*
            # The subshell ( ... ) ensures `cd` doesn't affect the loop
            (cd "$dir" && zip -r "../$zip_file_name" .)
          done

      - name: Create Release in private repo
        if: steps.version.outputs.version_found == 'true'
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
          CHANGELOG: ${{ steps.setver.outputs.changelog }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          gh release create "v$VERSION" \
            -R USLTD/aseprite-builds \
            --title "${{ steps.setver.outputs.title }}" \
            --notes-file <(echo "$CHANGELOG") \
            artifacts/*.zip
          echo "Release v$VERSION created in USLTD/aseprite-builds."
