name: Windows Build (Manual) - Test Version

permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Aseprite version (e.g., 1.3.6)'
        required: true
        type: string

jobs:
  precheck:
    name: Check for existing release
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
      version: ${{ steps.setver.outputs.version }}
    steps:
      - name: Read version input
        id: setver
        run: |
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
    
      - name: Query GitHub API for release
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v${{ steps.setver.outputs.version }}"
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG")
          if [ "$code" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build Aseprite
    runs-on: windows-latest
    needs: precheck
    if: needs.precheck.outputs.exists != 'true'

    env:
      VERSION: ${{ needs.precheck.outputs.version }}
      SCCACHE_GHA_ENABLED: "true"

    steps:

      - name: Cache sccache directory
        uses: actions/cache@v3
        with:
          path: |
            %USERPROFILE%\.cache\sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-sccache-


      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Set version
        id: version
        shell: pwsh
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $env:GITHUB_ENV

      - name: Checkout autobuild workflow repo
        uses: actions/checkout@v4

      - name: Clone Aseprite source
        run: |
          git clone --recursive --branch v1.3.5 https://github.com/aseprite/aseprite.git C:\aseprite

      - name: Setup MSVC
        if: env.SKIP != 'true'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      
      - name: Build with build.cmd --auto
        run: |
          cd C:\aseprite
          ./build.cmd --auto

      - name: Add libcrypto
        shell: pwsh
        run: |
          Push-Location C:\aseprite\build
          $libcrypto = $null
          if (Test-Path -Path "C:/Windows/SysWOW64/libcrypto-1_1-x64.dll") {
            $libcrypto = "C:/Windows/SysWOW64.libcrypto-1_1-x64.dll"
          } else {
            if (Test-Path -Path "C:/Windows/System32/libcrypto-1_1-x64.dll") {
              $libcrypto = "C:/Windows/System32/libcrypto-1_1-x64.dll"
            }
          }
          
          if ($libcrypto -ne $null) {
            Copy-Item -Path $libcrypto -Destination "./bin"
          }

      - name: Upload bin directory
        if: env.SKIP != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-v${{ env.VERSION }}-windows-x64
          path: C:\aseprite\build\bin

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    if: needs.precheck.outputs.exists != 'true' # Only create a release if one doesn't already exist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Aseprite Version from Precheck
        id: set_aseprite_version
        run: |
          # Use the version determined by the precheck job
          echo "ASEPRITE_VERSION=${{ needs.precheck.outputs.version }}" >> $GITHUB_ENV
          echo "Using Aseprite Version from precheck: ${{ needs.precheck.outputs.version }}"

      - name: Fetch Aseprite Changelog
        id: fetch_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the release body (changelog) from the official Aseprite repository
          CHANGELOG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/aseprite/aseprite/releases/tags/v${{ env.ASEPRITE_VERSION }}" | jq -r '.body')
          
          # Escape newlines for proper multiline string handling in outputs
          # And set it as an output for the next step
          echo "changelog_body<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "Changelog fetched for v${{ env.ASEPRITE_VERSION }}"

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # Download artifacts to this directory

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use gh CLI to create a new release
          # The '--generate-notes' flag is used to automatically generate release notes
          # based on the content of the fetched changelog
          gh release create "v${{ env.ASEPRITE_VERSION }}" \
            --title "Aseprite v${{ env.ASEPRITE_VERSION }} (Windows Build)" \
            --notes "${{ steps.fetch_changelog.outputs.changelog_body }}" \
            $(find artifacts -type f -name "aseprite-v${{ env.ASEPRITE_VERSION }}-windows-*.zip") # Attach all downloaded build artifacts
          echo "Release v${{ env.ASEPRITE_VERSION }} created."
